.PHONY: clean All

All:
	@echo "----------Building project:[ Section10Assignment - Debug ]----------"
	@cd "Section10Assignment" && "$(MAKE)" -f  "Section10Assignment.mk"
clean:
	@echo "----------Cleaning project:[ Section10Assignment - Debug ]----------"
	@cd "Section10Assignment" && "$(MAKE)" -f  "Section10Assignment.mk" clean
